name: RGCCR Notice Checker

on:
  schedule:
    - cron: "0 */1 * * *"  # Runs every 1 hour
  workflow_dispatch:  # Allows manual trigger

jobs:
  check_notices:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 1  # Fetch only the latest commit

      - name: Cache Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Notice Checker
        run: python RGCCR_Notice_Check.py
        env:
          EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          EMAIL_RECEIVER: ${{ secrets.EMAIL_RECEIVER }}

      - name: Commit and Push Notice Cache
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git remote set-url origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/MrBadasss/RGCCR_Notice_Check.git

          # Fetch latest changes to avoid conflicts
          git fetch origin main
          git checkout main
          git pull origin main --rebase

          # Check if file changed before committing
          git diff --quiet && exit 0

          git add data/previous_notices.txt
          git commit -m "Update cached notice section"
          git push origin main
        env:
          GH_PAT: ${{ secrets.GH_PAT }}

      - name: Send Error Log via Email (if any error)
        if: failure()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_SENDER }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          to: ${{ secrets.EMAIL_RECEIVER }}
          from: "RGCCR Notice Bot <${{ secrets.EMAIL_SENDER }}>"
          subject: "❌ RGCCR Notice Check Failed!"
          body: "An error occurred during the GitHub Actions run.\n\nCheck the logs for details: https://github.com/MrBadasss/RGCCR_Notice_Check/actions"
