name: RGCCR Notice Checker

on:
  schedule:
    - cron: "0 */6 * * *"  # Runs every 6 hours
  workflow_dispatch:  # Allows manual trigger

jobs:
  check_notices:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensures the full commit history is fetched to avoid conflicts

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --no-cache-dir -r requirements.txt

      - name: Backup Previous Notices
        run: |
          mkdir -p data
          cp data/previous_notices.txt data/previous_notices_backup.txt || echo "No previous notice file"

      - name: Run Notice Checker
        run: python RGCCR_Notice_Check.py
        env:
          EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          EMAIL_RECEIVER: ${{ secrets.EMAIL_RECEIVER }}

      - name: Commit and Push Notice Cache
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git remote set-url origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/MrBadasss/RGCCR_Notice_Check.git
          
          # Ensure the latest remote changes are incorporated
          git fetch origin main
          git reset --hard origin/main  # Forcefully sync local branch with remote
          
          git add data/previous_notices.txt
          git commit -m "Update cached notice section" || exit 0
          
          # Push the changes, forcing an update if necessary
          git push origin main --force
        env:
          GH_PAT: ${{ secrets.GH_PAT }}

      - name: Send Error Log via Email (if any error)
        if: failure()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_SENDER }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          to: ${{ secrets.EMAIL_RECEIVER }}
          from: "RGCCR Notice Bot <${{ secrets.EMAIL_SENDER }}>"
          subject: "❌ RGCCR Notice Check Failed!"
          body: "An error occurred during the GitHub Actions run.\n\nCheck the logs for details: https://github.com/MrBadasss/RGCCR_Notice_Check/actions"
